;; -*- coding:utf-8-unix; -*-
;; el-get-bundle.el
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; el-get-bundle
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; programming modes
(el-get-bundle web-mode)
(el-get-bundle yaml-mode)
(el-get-bundle js2-mode)
(el-get-bundle php-mode)
(el-get-bundle cperl-mode)
(el-get-bundle ruby-mode)
(el-get-bundle ruby-electric)
(el-get-bundle ruby-block)
(el-get-bundle inf-ruby)
(el-get-bundle ddskk)
(el-get-bundle ace-jump-mode)
(el-get-bundle sql-indent)
(el-get-bundle sql-complete)
(el-get-bundle sql-transform)
;; anything
(el-get-bundle emacswiki:anything)
(el-get-bundle emacswiki:anything-config)
(el-get-bundle emacswiki:anything-match-plugin)
(el-get-bundle emacswiki:anything-migemo)
(el-get-bundle emacswiki:anything-complete)
(el-get-bundle emacswiki:anything-show-completion)
(el-get-bundle emacswiki:anything-auto-install)
(el-get-bundle emacswiki:descbinds-anything)
(el-get-bundle emacswiki:anything-grep)
(el-get-bundle emacswiki:anything-menu)
(el-get-bundle emacswiki:anything-gtags)
(el-get-bundle emacswiki:ipa)
(el-get-bundle emacswiki:anything-ipa)
(el-get-bundle emacswiki:anything-obsolete)
(el-get-bundle ahakits/anything-c-moccur)

;; expansion
(el-get-bundle auto-complete)
(el-get-bundle moccur-edit)
(el-get-bundle wgrep)
(el-get-bundle undo-tree)
(el-get-bundle multiple-cursors)
(el-get-bundle volatile-highlights)
(el-get-bundle rainbow-delimiters)
(el-get-bundle exec-path-from-shell)
(el-get-bundle color-moccur)
(el-get-bundle yasnippet)
(el-get-bundle popwin)
(el-get-bundle redo+)
(el-get-bundle point-undo)
(el-get-bundle elscreen)
(el-get-bundle wdired)
(el-get-bundle direx)
(el-get-bundle flycheck)
